### ISSUE TITLE
OpenFromClipboardTests::testMember_2 fail intermittently on windows

### ISSUE THREAD

**Issue by vik-chand** [eclipse-jdt/eclipse.jdt.debug#142] opened 2022-09-30 04:57 UTC
org.eclipse.jdt.debug.tests.ui.OpenFromClipboardTests | testMember_2 | Failure | expected:<1> but was:<0>                                                                           junit.framework.AssertionFailedError: expected:<1> but was:<0>                                                  	at junit.framework.Assert.fail(Assert.java:57)                                                  	at junit.framework.Assert.failNotEquals(Assert.java:329)                                                  	at junit.framework.Assert.assertEquals(Assert.java:78)                                                  	at junit.framework.Assert.assertEquals(Assert.java:234)                                                  	at junit.framework.Assert.assertEquals(Assert.java:241)                                                  	at junit.framework.TestCase.assertEquals(TestCase.java:384)                                                  	at org.eclipse.jdt.debug.tests.ui.OpenFromClipboardTests.testMember_2(OpenFromClipboardTests.java:482)                                                  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                                                  	at  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                                  

```

**Comment by SarikaSinha** [comment] 2022-11-24 08:56
Duplicate of https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/28

**Closed by SarikaSinha** 2022-11-24 08:56 UTC
