### ISSUE TITLE
Cannot put breakpoint in lambda in Java Editor

### ISSUE THREAD

**Issue by gdany95** [eclipse-jdt/eclipse.jdt.debug#26] opened 2022-04-15 09:54 UTC
After I updated to a new version of Eclipse:
Version: 2022-03 (4.23.0)
Build id: 20220310-1457

I can no longer put breakpoints inside multi-line lambdas. Please see the video: https://vimeo.com/699728084/395899231e

The breakpoint is added at the end of the lambda. Prior to the update this was working. Also if I open the file in Text Editor instead of Java Editor it works. I was not able to find any setting for this behaviour in the Preferences.

**Comment by SarikaSinha** [comment] 2022-04-18 06:59
Duplicate of https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/6

Please try 4.24 M1 build or later.

**Closed by SarikaSinha** 2022-04-18 06:59 UTC
