### ISSUE TITLE
Remote debuging works drammaticaly slowly.

### ISSUE THREAD

**Issue by technician21** [eclipse-jdt/eclipse.jdt.debug#475] opened 2024-08-25 23:34 UTC
Remote debug starts in over minute.
The random breakpoints invoked for example in 3.5-7 and more minutes.
In this case debugger practically not working.
In comparison with intellij-community which starts in seconds, breakpoint triggered in up to 4-5 seconds on the same environment.
On remote application (Tomcat app server) decreased number of threads. In eclipse options e.g. show monitors, show threads is switched off. 

environment:
1. Eclipse for java EE and WTP:
Version: 2023-06 (4.28.0)
Build id: 20230608-1333

2. Built-in JDK: openjdk 17.0.7 2023-04-18
GNU/Linux Ubuntu 22.04

What additional information can i gather and provide to debug this issue.
Thanks

**Comment by jukzi** [comment] 2024-08-26 05:53
See https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md how to setup a workspace where you can debug the ide on your own. Create and post a minimal reproducer.

**Comment by rksharma1401** [comment] 2024-12-07 08:51
@jukzi @technician21 

May be this info can help

https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/39

**Comment by jukzi** [comment] 2024-12-09 07:10
no, i am closing this due to missing information. If the information is in 39 it would be a duplicate only anyway.

**Closed by jukzi** 2024-12-09 07:10 UTC
Labels: needinfo, performance
